version: "3.8"

services:
  db:
    build: db
    user: postgres
    expose:
      - 5432
    networks:
      backnet:
        ipv4_address: "192.168.0.10"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password

  api:
    build: app
    ports:
      - 8000:8000
    networks:
      backnet:
        ipv4_address: "192.168.0.11"
      frontnet:
        ipv4_address: "192.168.1.11"
    depends_on:
      db:
        condition: service_healthy

  proxy:
    build: proxy
    ports:
      - 8080:80
    networks:
      frontnet:
        ipv4_address: "192.168.1.10"
    depends_on:
      - api

volumes:
  db-data:

secrets:
  db-password:
    file: ./db/.db-password

networks:
  backnet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
  frontnet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"

